INSERT INTO actor (id,name,gender,birth) VALUES (0,"Kelly, Mr. James","male","1934-3-8");
INSERT INTO actor (id,name,gender,birth) VALUES (1,"Wilkes, Mrs. James (Ellen Needs)","female","1968-7-22");
INSERT INTO actor (id,name,gender,birth) VALUES (2,"Myles, Mr. Thomas Francis","male","1962-12-25");
INSERT INTO actor (id,name,gender,birth) VALUES (3,"Wirz, Mr. Albert","male","1982-7-26");
INSERT INTO actor (id,name,gender,birth) VALUES (4,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)","female","1975-3-10");
INSERT INTO actor (id,name,gender,birth) VALUES (5,"Svensson, Mr. Johan Cervin","male","1948-7-7");
INSERT INTO actor (id,name,gender,birth) VALUES (6,"Connolly, Miss. Kate","female","1985-6-18");
INSERT INTO actor (id,name,gender,birth) VALUES (7,"Caldwell, Mr. Albert Francis","male","1978-5-16");
INSERT INTO actor (id,name,gender,birth) VALUES (8,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)","female","1999-1-27");
INSERT INTO actor (id,name,gender,birth) VALUES (9,"Davies, Mr. John Samuel","male","1995-6-29");
INSERT INTO actor (id,name,gender,birth) VALUES (10,"Ilieff, Mr. Ylio","male","1973-10-16");
INSERT INTO actor (id,name,gender,birth) VALUES (11,"Jones, Mr. Charles Cresson","male","1930-10-6");
INSERT INTO actor (id,name,gender,birth) VALUES (12,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)","female","1980-6-28");
INSERT INTO actor (id,name,gender,birth) VALUES (13,"Howard, Mr. Benjamin","male","1994-8-2");
INSERT INTO actor (id,name,gender,birth) VALUES (14,"Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)","female","1936-4-10");
INSERT INTO actor (id,name,gender,birth) VALUES (15,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)","female","1940-3-11");
INSERT INTO actor (id,name,gender,birth) VALUES (16,"Keane, Mr. Daniel","male","1953-10-23");
INSERT INTO actor (id,name,gender,birth) VALUES (17,"Assaf, Mr. Gerios","male","1936-6-7");
INSERT INTO actor (id,name,gender,birth) VALUES (18,"Ilmakangas, Miss. Ida Livija","female","1996-8-15");
INSERT INTO actor (id,name,gender,birth) VALUES (19,"Assaf Khalil, Mrs. Mariana (Miriam ) ","female","1954-11-15");
INSERT INTO actor (id,name,gender,birth) VALUES (20,"Rothschild, Mr. Martin","male","1993-4-7");
INSERT INTO actor (id,name,gender,birth) VALUES (21,"Olsen, Master. Artur Karl","male","1999-8-18");
INSERT INTO actor (id,name,gender,birth) VALUES (22,"Flegenheim, Mrs. Alfred (Antoinette)","female","1970-12-19");
INSERT INTO actor (id,name,gender,birth) VALUES (23,"Williams, Mr. Richard Norris II","male","1962-8-27");
INSERT INTO actor (id,name,gender,birth) VALUES (24,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)","female","1960-10-22");
INSERT INTO actor (id,name,gender,birth) VALUES (25,"Robins, Mr. Alexander A","male","1967-10-25");
INSERT INTO actor (id,name,gender,birth) VALUES (26,"Ostby, Miss. Helene Ragnhild","female","1996-3-4");
INSERT INTO actor (id,name,gender,birth) VALUES (27,"Daher, Mr. Shedid","male","1960-7-9");
INSERT INTO actor (id,name,gender,birth) VALUES (28,"Brady, Mr. John Bertram","male","1962-1-23");
INSERT INTO actor (id,name,gender,birth) VALUES (29,"Samaan, Mr. Elias","male","1974-8-11");
INSERT INTO actor (id,name,gender,birth) VALUES (30,"Louch, Mr. Charles Alexander","male","1928-2-28");
INSERT INTO actor (id,name,gender,birth) VALUES (31,"Jefferys, Mr. Clifford Thomas","male","1928-10-23");
INSERT INTO actor (id,name,gender,birth) VALUES (32,"Dean, Mrs. Bertram (Eva Georgetta Light)","female","1966-6-7");
INSERT INTO actor (id,name,gender,birth) VALUES (33,"Johnston, Mrs. Andrew G (Elizabeth Lily  Watson) ","female","1920-9-18");
INSERT INTO actor (id,name,gender,birth) VALUES (34,"Mock, Mr. Philipp Edmund","male","1959-4-28");
INSERT INTO actor (id,name,gender,birth) VALUES (35,"Katavelas, Mr. Vassilios (Catavelas Vassilios ) ","male","1935-1-15");
INSERT INTO actor (id,name,gender,birth) VALUES (36,"Roth, Miss. Sarah A","female","1953-7-23");
INSERT INTO actor (id,name,gender,birth) VALUES (37,"Cacic, Miss. Manda","female","1928-11-8");
INSERT INTO actor (id,name,gender,birth) VALUES (38,"Sap, Mr. Julius","male","1947-1-22");
INSERT INTO actor (id,name,gender,birth) VALUES (39,"Hee, Mr. Ling","male","1934-6-16");
INSERT INTO actor (id,name,gender,birth) VALUES (40,"Karun, Mr. Franz","male","1960-10-1");
INSERT INTO actor (id,name,gender,birth) VALUES (41,"Franklin, Mr. Thomas Parham","male","1972-9-15");
INSERT INTO actor (id,name,gender,birth) VALUES (42,"Goldsmith, Mr. Nathan","male","1970-9-14");
INSERT INTO actor (id,name,gender,birth) VALUES (43,"Corbett, Mrs. Walter H (Irene Colvin)","female","1995-1-5");
INSERT INTO actor (id,name,gender,birth) VALUES (44,"Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)","female","1930-4-9");
INSERT INTO actor (id,name,gender,birth) VALUES (45,"Peltomaki, Mr. Nikolai Johannes","male","1965-1-21");
INSERT INTO actor (id,name,gender,birth) VALUES (46,"Chevre, Mr. Paul Romaine","male","1969-3-2");
INSERT INTO actor (id,name,gender,birth) VALUES (47,"Shaughnessy, Mr. Patrick","male","1961-10-4");
INSERT INTO actor (id,name,gender,birth) VALUES (48,"Bucknell, Mrs. William Robert (Emma Eliza Ward)","female","1956-12-24");
INSERT INTO actor (id,name,gender,birth) VALUES (49,"Coutts, Mrs. William (Winnie Minnie  Treanor) ","female","1942-3-11");
INSERT INTO actor (id,name,gender,birth) VALUES (50,"Smith, Mr. Lucien Philip","male","1954-12-21");
INSERT INTO actor (id,name,gender,birth) VALUES (51,"Pulbaum, Mr. Franz","male","1968-1-14");
INSERT INTO actor (id,name,gender,birth) VALUES (52,"Hocking, Miss. Ellen Nellie  ","female","1998-1-16");
INSERT INTO actor (id,name,gender,birth) VALUES (53,"Fortune, Miss. Ethel Flora","female","1965-10-4");
INSERT INTO actor (id,name,gender,birth) VALUES (54,"Mangiavacchi, Mr. Serafino Emilio","male","1966-4-29");
INSERT INTO actor (id,name,gender,birth) VALUES (55,"Rice, Master. Albert","male","1927-7-19");
INSERT INTO actor (id,name,gender,birth) VALUES (56,"Cor, Mr. Bartol","male","1927-4-17");
INSERT INTO actor (id,name,gender,birth) VALUES (57,"Abelseth, Mr. Olaus Jorgensen","male","1964-2-3");
INSERT INTO actor (id,name,gender,birth) VALUES (58,"Davison, Mr. Thomas Henry","male","1934-5-9");
INSERT INTO actor (id,name,gender,birth) VALUES (59,"Chaudanson, Miss. Victorine","female","1995-1-15");
INSERT INTO actor (id,name,gender,birth) VALUES (60,"Dika, Mr. Mirko","male","1948-10-4");
INSERT INTO actor (id,name,gender,birth) VALUES (61,"McCrae, Mr. Arthur Gordon","male","1980-4-18");
INSERT INTO actor (id,name,gender,birth) VALUES (62,"Bjorklund, Mr. Ernst Herbert","male","1944-5-3");
INSERT INTO actor (id,name,gender,birth) VALUES (63,"Bradley, Miss. Bridget Delia","female","1950-4-7");
INSERT INTO actor (id,name,gender,birth) VALUES (64,"Ryerson, Master. John Borie","male","1961-9-16");
INSERT INTO actor (id,name,gender,birth) VALUES (65,"Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller)","female","1953-3-1");
INSERT INTO actor (id,name,gender,birth) VALUES (66,"Burns, Miss. Mary Delia","female","1972-7-21");
INSERT INTO actor (id,name,gender,birth) VALUES (67,"Moore, Mr. Clarence Bloomfield","male","1922-9-7");
INSERT INTO actor (id,name,gender,birth) VALUES (68,"Tucker, Mr. Gilbert Milligan Jr","male","1981-7-17");
INSERT INTO actor (id,name,gender,birth) VALUES (69,"Fortune, Mrs. Mark (Mary McDougald)","female","1971-6-12");
INSERT INTO actor (id,name,gender,birth) VALUES (70,"Mulvihill, Miss. Bertha E","female","1948-12-9");
INSERT INTO actor (id,name,gender,birth) VALUES (71,"Minkoff, Mr. Lazar","male","1931-12-17");
INSERT INTO actor (id,name,gender,birth) VALUES (72,"Nieminen, Miss. Manta Josefina","female","1972-1-24");
INSERT INTO actor (id,name,gender,birth) VALUES (73,"Ovies y Rodriguez, Mr. Servando","male","1983-2-14");
INSERT INTO actor (id,name,gender,birth) VALUES (74,"Geiger, Miss. Amalie","female","1934-12-10");
INSERT INTO actor (id,name,gender,birth) VALUES (75,"Keeping, Mr. Edwin","male","1962-4-28");
INSERT INTO actor (id,name,gender,birth) VALUES (76,"Miles, Mr. Frank","male","1927-9-17");
INSERT INTO actor (id,name,gender,birth) VALUES (77,"Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)","female","1987-3-1");
INSERT INTO actor (id,name,gender,birth) VALUES (78,"Aldworth, Mr. Charles Augustus","male","1993-10-11");
INSERT INTO actor (id,name,gender,birth) VALUES (79,"Doyle, Miss. Elizabeth","female","1941-2-5");
INSERT INTO actor (id,name,gender,birth) VALUES (80,"Boulos, Master. Akar","male","1980-8-24");
INSERT INTO actor (id,name,gender,birth) VALUES (81,"Straus, Mr. Isidor","male","1989-7-13");
INSERT INTO actor (id,name,gender,birth) VALUES (82,"Case, Mr. Howard Brown","male","1923-11-9");
INSERT INTO actor (id,name,gender,birth) VALUES (83,"Demetri, Mr. Marinko","male","1974-8-25");
INSERT INTO actor (id,name,gender,birth) VALUES (84,"Lamb, Mr. John Joseph","male","1958-9-14");
INSERT INTO actor (id,name,gender,birth) VALUES (85,"Khalil, Mr. Betros","male","1924-4-8");
INSERT INTO actor (id,name,gender,birth) VALUES (86,"Barry, Miss. Julia","female","1940-2-9");
INSERT INTO actor (id,name,gender,birth) VALUES (87,"Badman, Miss. Emily Louisa","female","1972-6-5");
INSERT INTO actor (id,name,gender,birth) VALUES (88,"O'Donoghue, Ms. Bridget","female","1935-11-13");
INSERT INTO actor (id,name,gender,birth) VALUES (89,"Wells, Master. Ralph Lester","male","1931-1-24");
INSERT INTO actor (id,name,gender,birth) VALUES (90,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judith Andersson)","female","1994-11-23");
INSERT INTO actor (id,name,gender,birth) VALUES (91,"Pedersen, Mr. Olaf","male","1956-3-15");
INSERT INTO actor (id,name,gender,birth) VALUES (92,"Davidson, Mrs. Thornton (Orian Hays)","female","1935-8-19");
INSERT INTO actor (id,name,gender,birth) VALUES (93,"Guest, Mr. Robert","male","1961-2-10");
INSERT INTO actor (id,name,gender,birth) VALUES (94,"Birnbaum, Mr. Jakob","male","1981-8-7");
INSERT INTO actor (id,name,gender,birth) VALUES (95,"Tenglin, Mr. Gunnar Isidor","male","1936-5-5");
INSERT INTO actor (id,name,gender,birth) VALUES (96,"Cavendish, Mrs. Tyrell William (Julia Florence Siegel)","female","1979-8-6");
INSERT INTO actor (id,name,gender,birth) VALUES (97,"Makinen, Mr. Kalle Edvard","male","1965-10-7");
INSERT INTO actor (id,name,gender,birth) VALUES (98,"Braf, Miss. Elin Ester Maria","female","1982-10-14");
INSERT INTO actor (id,name,gender,birth) VALUES (99,"Nancarrow, Mr. William Henry","male","1928-5-1");
INSERT INTO actor (id,name,gender,birth) VALUES (100,"Stengel, Mrs. Charles Emil Henry (Annie May Morris)","female","1974-10-23");
INSERT INTO actor (id,name,gender,birth) VALUES (101,"Weisz, Mr. Leopold","male","1966-7-14");
INSERT INTO actor (id,name,gender,birth) VALUES (102,"Foley, Mr. William","male","1921-12-28");
INSERT INTO actor (id,name,gender,birth) VALUES (103,"Johansson Palmquist, Mr. Oskar Leander","male","1989-9-24");
INSERT INTO actor (id,name,gender,birth) VALUES (104,"Thomas, Mrs. Alexander (Thamine Thelma ) ","female","1987-10-6");
INSERT INTO actor (id,name,gender,birth) VALUES (105,"Holthen, Mr. Johan Martin","male","1950-2-18");
INSERT INTO actor (id,name,gender,birth) VALUES (106,"Buckley, Mr. Daniel","male","1996-8-29");
INSERT INTO actor (id,name,gender,birth) VALUES (107,"Ryan, Mr. Edward","male","1988-12-17");
INSERT INTO actor (id,name,gender,birth) VALUES (108,"Willer, Mr. Aaron (Abi Weller ) ","male","1999-1-21");
INSERT INTO actor (id,name,gender,birth) VALUES (109,"Swane, Mr. George","male","1964-4-27");
INSERT INTO actor (id,name,gender,birth) VALUES (110,"Stanton, Mr. Samuel Ward","male","1984-2-23");
INSERT INTO actor (id,name,gender,birth) VALUES (111,"Shine, Miss. Ellen Natalia","female","1995-5-21");
INSERT INTO actor (id,name,gender,birth) VALUES (112,"Evans, Miss. Edith Corse","female","1961-6-2");
INSERT INTO actor (id,name,gender,birth) VALUES (113,"Buckley, Miss. Katherine","female","1988-11-14");
INSERT INTO actor (id,name,gender,birth) VALUES (114,"Straus, Mrs. Isidor (Rosalie Ida Blun)","female","1932-7-23");
INSERT INTO actor (id,name,gender,birth) VALUES (115,"Chronopoulos, Mr. Demetrios","male","1993-8-7");
INSERT INTO actor (id,name,gender,birth) VALUES (116,"Thomas, Mr. John","male","1973-1-19");
INSERT INTO actor (id,name,gender,birth) VALUES (117,"Sandstrom, Miss. Beatrice Irene","female","1976-3-3");
INSERT INTO actor (id,name,gender,birth) VALUES (118,"Beattie, Mr. Thomson","male","1945-4-18");
INSERT INTO actor (id,name,gender,birth) VALUES (119,"Chapman, Mrs. John Henry (Sara Elizabeth Lawry)","female","1960-1-17");
INSERT INTO actor (id,name,gender,birth) VALUES (120,"Watt, Miss. Bertha J","female","1982-2-1");
INSERT INTO actor (id,name,gender,birth) VALUES (121,"Kiernan, Mr. John","male","1998-7-11");
INSERT INTO actor (id,name,gender,birth) VALUES (122,"Schabert, Mrs. Paul (Emma Mock)","female","1929-3-13");
INSERT INTO actor (id,name,gender,birth) VALUES (123,"Carver, Mr. Alfred John","male","1922-9-15");
INSERT INTO actor (id,name,gender,birth) VALUES (124,"Kennedy, Mr. John","male","1977-9-11");
INSERT INTO actor (id,name,gender,birth) VALUES (125,"Cribb, Miss. Laura Alice","female","1973-4-21");
INSERT INTO actor (id,name,gender,birth) VALUES (126,"Brobeck, Mr. Karl Rudolf","male","1927-11-2");
INSERT INTO actor (id,name,gender,birth) VALUES (127,"McCoy, Miss. Alicia","female","1962-11-2");
INSERT INTO actor (id,name,gender,birth) VALUES (128,"Bowenur, Mr. Solomon","male","1931-11-19");
INSERT INTO actor (id,name,gender,birth) VALUES (129,"Petersen, Mr. Marius","male","1977-1-27");
INSERT INTO actor (id,name,gender,birth) VALUES (130,"Spinner, Mr. Henry John","male","1923-8-1");
INSERT INTO actor (id,name,gender,birth) VALUES (131,"Gracie, Col. Archibald IV","male","1976-5-12");
INSERT INTO actor (id,name,gender,birth) VALUES (132,"Lefebre, Mrs. Frank (Frances)","female","1941-12-21");
INSERT INTO actor (id,name,gender,birth) VALUES (133,"Thomas, Mr. Charles P","male","1982-4-22");
INSERT INTO actor (id,name,gender,birth) VALUES (134,"Dintcheff, Mr. Valtcho","male","1987-12-21");
INSERT INTO actor (id,name,gender,birth) VALUES (135,"Carlsson, Mr. Carl Robert","male","1925-4-20");
INSERT INTO actor (id,name,gender,birth) VALUES (136,"Zakarian, Mr. Mapriededer","male","1962-9-29");
INSERT INTO actor (id,name,gender,birth) VALUES (137,"Schmidt, Mr. August","male","1973-2-6");
INSERT INTO actor (id,name,gender,birth) VALUES (138,"Drapkin, Miss. Jennie","female","1920-10-27");
INSERT INTO actor (id,name,gender,birth) VALUES (139,"Goodwin, Mr. Charles Frederick","male","1957-6-8");
INSERT INTO actor (id,name,gender,birth) VALUES (140,"Goodwin, Miss. Jessie Allis","female","1967-9-20");
INSERT INTO actor (id,name,gender,birth) VALUES (141,"Daniels, Miss. Sarah","female","1947-9-25");
INSERT INTO actor (id,name,gender,birth) VALUES (142,"Ryerson, Mr. Arthur Larned","male","1981-6-16");
INSERT INTO actor (id,name,gender,birth) VALUES (143,"Beauchamp, Mr. Henry James","male","1950-3-12");
INSERT INTO actor (id,name,gender,birth) VALUES (144,"Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lingrey ) ","male","1985-7-13");
INSERT INTO actor (id,name,gender,birth) VALUES (145,"Vander Planke, Mr. Julius","male","1964-4-27");
INSERT INTO actor (id,name,gender,birth) VALUES (146,"Hilliard, Mr. Herbert Henry","male","1925-4-6");
INSERT INTO actor (id,name,gender,birth) VALUES (147,"Davies, Mr. Evan","male","1941-7-10");
INSERT INTO actor (id,name,gender,birth) VALUES (148,"Crafton, Mr. John Bertram","male","1971-11-26");
INSERT INTO actor (id,name,gender,birth) VALUES (149,"Lahtinen, Rev. William","male","1923-5-26");
INSERT INTO actor (id,name,gender,birth) VALUES (150,"Earnshaw, Mrs. Boulton (Olive Potter)","female","1991-4-26");
INSERT INTO actor (id,name,gender,birth) VALUES (151,"Matinoff, Mr. Nicola","male","1959-1-18");
INSERT INTO actor (id,name,gender,birth) VALUES (152,"Storey, Mr. Thomas","male","1986-1-14");
INSERT INTO actor (id,name,gender,birth) VALUES (153,"Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)","female","1929-8-12");
INSERT INTO actor (id,name,gender,birth) VALUES (154,"Asplund, Master. Filip Oscar","male","1925-10-5");
INSERT INTO actor (id,name,gender,birth) VALUES (155,"Duquemin, Mr. Joseph","male","1958-12-15");
INSERT INTO actor (id,name,gender,birth) VALUES (156,"Bird, Miss. Ellen","female","1998-4-19");
INSERT INTO actor (id,name,gender,birth) VALUES (157,"Lundin, Miss. Olga Elida","female","1943-9-28");
INSERT INTO actor (id,name,gender,birth) VALUES (158,"Borebank, Mr. John James","male","1983-2-18");
INSERT INTO actor (id,name,gender,birth) VALUES (159,"Peacock, Mrs. Benjamin (Edith Nile)","female","1968-6-7");
INSERT INTO actor (id,name,gender,birth) VALUES (160,"Smyth, Miss. Julia","female","1935-8-15");
INSERT INTO actor (id,name,gender,birth) VALUES (161,"Touma, Master. Georges Youssef","male","1923-12-10");
INSERT INTO actor (id,name,gender,birth) VALUES (162,"Wright, Miss. Marion","female","1934-12-27");
INSERT INTO actor (id,name,gender,birth) VALUES (163,"Pearce, Mr. Ernest","male","1984-4-1");
INSERT INTO actor (id,name,gender,birth) VALUES (164,"Peruschitz, Rev. Joseph Maria","male","1965-9-1");
INSERT INTO actor (id,name,gender,birth) VALUES (165,"Kink-Heilmann, Mrs. Anton (Luise Heilmann)","female","1929-5-7");
INSERT INTO actor (id,name,gender,birth) VALUES (166,"Brandeis, Mr. Emil","male","1960-1-9");
INSERT INTO actor (id,name,gender,birth) VALUES (167,"Ford, Mr. Edward Watson","male","1978-6-16");
INSERT INTO actor (id,name,gender,birth) VALUES (168,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)","female","1923-5-7");
INSERT INTO actor (id,name,gender,birth) VALUES (169,"Hellstrom, Miss. Hilda Maria","female","1924-10-23");
INSERT INTO actor (id,name,gender,birth) VALUES (170,"Lithman, Mr. Simon","male","1933-2-27");
INSERT INTO actor (id,name,gender,birth) VALUES (171,"Zakarian, Mr. Ortin","male","1943-10-17");
INSERT INTO actor (id,name,gender,birth) VALUES (172,"Dyker, Mr. Adolf Fredrik","male","1957-8-28");
INSERT INTO actor (id,name,gender,birth) VALUES (173,"Torfa, Mr. Assad","male","1935-12-12");
INSERT INTO actor (id,name,gender,birth) VALUES (174,"Asplund, Mr. Carl Oscar Vilhelm Gustafsson","male","1954-10-28");
INSERT INTO actor (id,name,gender,birth) VALUES (175,"Brown, Miss. Edith Eileen","female","1952-9-9");
INSERT INTO actor (id,name,gender,birth) VALUES (176,"Sincock, Miss. Maude","female","1963-7-5");
INSERT INTO actor (id,name,gender,birth) VALUES (177,"Stengel, Mr. Charles Emil Henry","male","1995-7-3");
INSERT INTO actor (id,name,gender,birth) VALUES (178,"Becker, Mrs. Allen Oliver (Nellie E Baumgardner)","female","1946-6-16");
INSERT INTO actor (id,name,gender,birth) VALUES (179,"Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)","female","1969-5-9");
INSERT INTO actor (id,name,gender,birth) VALUES (180,"McCrie, Mr. James Matthew","male","1955-9-13");
INSERT INTO actor (id,name,gender,birth) VALUES (181,"Compton, Mr. Alexander Taylor Jr","male","1966-5-1");
INSERT INTO actor (id,name,gender,birth) VALUES (182,"Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)","female","1961-9-11");
INSERT INTO actor (id,name,gender,birth) VALUES (183,"Lane, Mr. Patrick","male","1927-1-19");
INSERT INTO actor (id,name,gender,birth) VALUES (184,"Douglas, Mrs. Frederick Charles (Mary Helene Baxter)","female","1928-6-3");
INSERT INTO actor (id,name,gender,birth) VALUES (185,"Maybery, Mr. Frank Hubert","male","1966-11-12");
INSERT INTO actor (id,name,gender,birth) VALUES (186,"Phillips, Miss. Alice Frances Louisa","female","1921-7-8");
INSERT INTO actor (id,name,gender,birth) VALUES (187,"Davies, Mr. Joseph","male","1968-7-26");
INSERT INTO actor (id,name,gender,birth) VALUES (188,"Sage, Miss. Ada","female","1937-12-19");
INSERT INTO actor (id,name,gender,birth) VALUES (189,"Veal, Mr. James","male","1999-11-12");
INSERT INTO actor (id,name,gender,birth) VALUES (190,"Angle, Mr. William A","male","1982-9-13");
INSERT INTO actor (id,name,gender,birth) VALUES (191,"Salomon, Mr. Abraham L","male","1931-6-24");
INSERT INTO actor (id,name,gender,birth) VALUES (192,"van Billiard, Master. Walter John","male","1933-9-20");
INSERT INTO actor (id,name,gender,birth) VALUES (193,"Lingane, Mr. John","male","1926-11-15");
INSERT INTO actor (id,name,gender,birth) VALUES (194,"Drew, Master. Marshall Brines","male","1999-10-22");
INSERT INTO actor (id,name,gender,birth) VALUES (195,"Karlsson, Mr. Julius Konrad Eugen","male","1997-7-6");
INSERT INTO actor (id,name,gender,birth) VALUES (196,"Spedden, Master. Robert Douglas","male","1940-3-2");
INSERT INTO actor (id,name,gender,birth) VALUES (197,"Nilsson, Miss. Berta Olivia","female","1921-9-15");
INSERT INTO actor (id,name,gender,birth) VALUES (198,"Baimbrigge, Mr. Charles Robert","male","1953-8-11");
INSERT INTO actor (id,name,gender,birth) VALUES (199,"Rasmussen, Mrs. (Lena Jacobsen Solvang)","female","1974-5-10");
INSERT INTO actor (id,name,gender,birth) VALUES (200,"Murphy, Miss. Nora","female","1993-10-8");
INSERT INTO actor (id,name,gender,birth) VALUES (201,"Danbom, Master. Gilbert Sigvard Emanuel","male","1987-11-28");
INSERT INTO actor (id,name,gender,birth) VALUES (202,"Astor, Col. John Jacob","male","1985-1-13");
INSERT INTO actor (id,name,gender,birth) VALUES (203,"Quick, Miss. Winifred Vera","female","1963-2-28");
INSERT INTO actor (id,name,gender,birth) VALUES (204,"Andrew, Mr. Frank Thomas","male","1942-5-27");
INSERT INTO actor (id,name,gender,birth) VALUES (205,"Omont, Mr. Alfred Fernand","male","1951-11-22");
INSERT INTO actor (id,name,gender,birth) VALUES (206,"McGowan, Miss. Katherine","female","1996-4-13");
INSERT INTO actor (id,name,gender,birth) VALUES (207,"Collett, Mr. Sidney C Stuart","male","1932-11-11");
INSERT INTO actor (id,name,gender,birth) VALUES (208,"Rosenbaum, Miss. Edith Louise","female","1969-9-16");
INSERT INTO actor (id,name,gender,birth) VALUES (209,"Delalic, Mr. Redjo","male","1938-7-25");
INSERT INTO actor (id,name,gender,birth) VALUES (210,"Andersen, Mr. Albert Karvin","male","1937-8-25");
INSERT INTO actor (id,name,gender,birth) VALUES (211,"Finoli, Mr. Luigi","male","1969-9-19");
INSERT INTO actor (id,name,gender,birth) VALUES (212,"Deacon, Mr. Percy William","male","1944-3-3");
INSERT INTO actor (id,name,gender,birth) VALUES (213,"Howard, Mrs. Benjamin (Ellen Truelove Arman)","female","1953-6-1");
INSERT INTO actor (id,name,gender,birth) VALUES (214,"Andersson, Miss. Ida Augusta Margareta","female","1929-2-18");
INSERT INTO actor (id,name,gender,birth) VALUES (215,"Head, Mr. Christopher","male","1957-3-28");
INSERT INTO actor (id,name,gender,birth) VALUES (216,"Mahon, Miss. Bridget Delia","female","1923-6-1");
INSERT INTO actor (id,name,gender,birth) VALUES (217,"Wick, Mr. George Dennick","male","1994-2-3");
INSERT INTO actor (id,name,gender,birth) VALUES (218,"Widener, Mrs. George Dunton (Eleanor Elkins)","female","1928-4-3");
INSERT INTO actor (id,name,gender,birth) VALUES (219,"Thomson, Mr. Alexander Morrison","male","1982-1-6");
INSERT INTO actor (id,name,gender,birth) VALUES (220,"Duran y More, Miss. Florentina","female","1982-2-2");
INSERT INTO actor (id,name,gender,birth) VALUES (221,"Reynolds, Mr. Harold J","male","1988-9-9");
INSERT INTO actor (id,name,gender,birth) VALUES (222,"Cook, Mrs. (Selena Rogers)","female","1932-10-14");
INSERT INTO actor (id,name,gender,birth) VALUES (223,"Karlsson, Mr. Einar Gervasius","male","1931-4-21");
INSERT INTO actor (id,name,gender,birth) VALUES (224,"Candee, Mrs. Edward (Helen Churchill Hungerford)","female","1928-12-24");
INSERT INTO actor (id,name,gender,birth) VALUES (225,"Moubarek, Mrs. George (Omine Amenia  Alexander) ","female","1983-1-3");
INSERT INTO actor (id,name,gender,birth) VALUES (226,"Asplund, Mr. Johan Charles","male","1932-8-4");
INSERT INTO actor (id,name,gender,birth) VALUES (227,"McNeill, Miss. Bridget","female","1945-3-15");
INSERT INTO actor (id,name,gender,birth) VALUES (228,"Everett, Mr. Thomas James","male","1932-12-27");
INSERT INTO actor (id,name,gender,birth) VALUES (229,"Hocking, Mr. Samuel James Metcalfe","male","1975-3-17");
INSERT INTO actor (id,name,gender,birth) VALUES (230,"Sweet, Mr. George Frederick","male","1991-9-21");
INSERT INTO actor (id,name,gender,birth) VALUES (231,"Willard, Miss. Constance","female","1954-4-26");
INSERT INTO actor (id,name,gender,birth) VALUES (232,"Wiklund, Mr. Karl Johan","male","1956-4-27");
INSERT INTO actor (id,name,gender,birth) VALUES (233,"Linehan, Mr. Michael","male","1991-3-16");
INSERT INTO actor (id,name,gender,birth) VALUES (234,"Cumings, Mr. John Bradley","male","1929-3-12");
INSERT INTO actor (id,name,gender,birth) VALUES (235,"Vendel, Mr. Olof Edvin","male","1923-11-29");
INSERT INTO actor (id,name,gender,birth) VALUES (236,"Warren, Mr. Frank Manley","male","1997-8-3");
INSERT INTO actor (id,name,gender,birth) VALUES (237,"Baccos, Mr. Raffull","male","1942-8-15");
INSERT INTO actor (id,name,gender,birth) VALUES (238,"Hiltunen, Miss. Marta","female","1976-5-9");
INSERT INTO actor (id,name,gender,birth) VALUES (239,"Douglas, Mrs. Walter Donald (Mahala Dutton)","female","1925-3-20");
INSERT INTO actor (id,name,gender,birth) VALUES (240,"Lindstrom, Mrs. Carl Johan (Sigrid Posse)","female","1989-2-17");
INSERT INTO actor (id,name,gender,birth) VALUES (241,"Christy, Mrs. (Alice Frances)","female","1994-12-25");
INSERT INTO actor (id,name,gender,birth) VALUES (242,"Spedden, Mr. Frederic Oakley","male","1990-8-15");
INSERT INTO actor (id,name,gender,birth) VALUES (243,"Hyman, Mr. Abraham","male","1950-1-1");
INSERT INTO actor (id,name,gender,birth) VALUES (244,"Johnston, Master. William Arthur Willie  ","male","1941-6-2");
INSERT INTO actor (id,name,gender,birth) VALUES (245,"Kenyon, Mr. Frederick R","male","1970-10-29");
INSERT INTO actor (id,name,gender,birth) VALUES (246,"Karnes, Mrs. J Frank (Claire Bennett)","female","1937-5-17");
INSERT INTO actor (id,name,gender,birth) VALUES (247,"Drew, Mr. James Vivian","male","1986-5-25");
INSERT INTO actor (id,name,gender,birth) VALUES (248,"Hold, Mrs. Stephen (Annie Margaret Hill)","female","1989-3-21");
INSERT INTO actor (id,name,gender,birth) VALUES (249,"Khalil, Mrs. Betros (Zahie Maria  Elias) ","female","1928-9-4");
INSERT INTO actor (id,name,gender,birth) VALUES (250,"West, Miss. Barbara J","female","1995-12-29");
INSERT INTO actor (id,name,gender,birth) VALUES (251,"Abrahamsson, Mr. Abraham August Johannes","male","1973-10-14");
INSERT INTO actor (id,name,gender,birth) VALUES (252,"Clark, Mr. Walter Miller","male","1975-5-10");
INSERT INTO actor (id,name,gender,birth) VALUES (253,"Salander, Mr. Karl Johan","male","1957-7-6");
INSERT INTO actor (id,name,gender,birth) VALUES (254,"Wenzel, Mr. Linhart","male","1967-4-23");
INSERT INTO actor (id,name,gender,birth) VALUES (255,"MacKay, Mr. George William","male","1954-11-6");
INSERT INTO actor (id,name,gender,birth) VALUES (256,"Mahon, Mr. John","male","1996-12-13");
INSERT INTO actor (id,name,gender,birth) VALUES (257,"Niklasson, Mr. Samuel","male","1947-5-5");
INSERT INTO actor (id,name,gender,birth) VALUES (258,"Bentham, Miss. Lilian W","female","1972-10-16");
INSERT INTO actor (id,name,gender,birth) VALUES (259,"Midtsjo, Mr. Karl Albert","male","1993-2-3");
INSERT INTO actor (id,name,gender,birth) VALUES (260,"de Messemaeker, Mr. Guillaume Joseph","male","1956-8-26");
INSERT INTO actor (id,name,gender,birth) VALUES (261,"Nilsson, Mr. August Ferdinand","male","1966-8-11");
INSERT INTO actor (id,name,gender,birth) VALUES (262,"Wells, Mrs. Arthur Henry (Addie  Dart Trevaskis) ","female","1963-8-22");
INSERT INTO actor (id,name,gender,birth) VALUES (263,"Klasen, Miss. Gertrud Emilia","female","1938-3-24");
INSERT INTO actor (id,name,gender,birth) VALUES (264,"Portaluppi, Mr. Emilio Ilario Giuseppe","male","1983-10-7");
INSERT INTO actor (id,name,gender,birth) VALUES (265,"Lyntakoff, Mr. Stanko","male","1979-7-27");
INSERT INTO actor (id,name,gender,birth) VALUES (266,"Chisholm, Mr. Roderick Robert Crispin","male","1922-5-21");
INSERT INTO actor (id,name,gender,birth) VALUES (267,"Warren, Mr. Charles William","male","1939-7-3");
INSERT INTO actor (id,name,gender,birth) VALUES (268,"Howard, Miss. May Elizabeth","female","1968-7-21");
INSERT INTO actor (id,name,gender,birth) VALUES (269,"Pokrnic, Mr. Mate","male","1967-12-8");
INSERT INTO actor (id,name,gender,birth) VALUES (270,"McCaffry, Mr. Thomas Francis","male","1950-10-11");
INSERT INTO actor (id,name,gender,birth) VALUES (271,"Fox, Mr. Patrick","male","1930-11-20");
INSERT INTO actor (id,name,gender,birth) VALUES (272,"Clark, Mrs. Walter Miller (Virginia McDowell)","female","1941-10-10");
INSERT INTO actor (id,name,gender,birth) VALUES (273,"Lennon, Miss. Mary","female","1956-6-20");
INSERT INTO actor (id,name,gender,birth) VALUES (274,"Saade, Mr. Jean Nassr","male","1993-10-11");
INSERT INTO actor (id,name,gender,birth) VALUES (275,"Bryhl, Miss. Dagmar Jenny Ingeborg ","female","1921-3-7");
INSERT INTO actor (id,name,gender,birth) VALUES (276,"Parker, Mr. Clifford Richard","male","1995-6-29");
INSERT INTO actor (id,name,gender,birth) VALUES (277,"Faunthorpe, Mr. Harry","male","1937-7-29");
INSERT INTO actor (id,name,gender,birth) VALUES (278,"Ware, Mr. John James","male","1944-11-12");
INSERT INTO actor (id,name,gender,birth) VALUES (279,"Oxenham, Mr. Percy Thomas","male","1993-1-19");
INSERT INTO actor (id,name,gender,birth) VALUES (280,"Oreskovic, Miss. Jelka","female","1995-4-26");
INSERT INTO actor (id,name,gender,birth) VALUES (281,"Peacock, Master. Alfred Edward","male","1968-5-11");
INSERT INTO actor (id,name,gender,birth) VALUES (282,"Fleming, Miss. Honora","female","1972-10-5");
INSERT INTO actor (id,name,gender,birth) VALUES (283,"Touma, Miss. Maria Youssef","female","1958-1-19");
INSERT INTO actor (id,name,gender,birth) VALUES (284,"Rosblom, Miss. Salli Helena","female","1981-7-13");
INSERT INTO actor (id,name,gender,birth) VALUES (285,"Dennis, Mr. William","male","1921-5-20");
INSERT INTO actor (id,name,gender,birth) VALUES (286,"Franklin, Mr. Charles (Charles Fardon)","male","1944-2-29");
INSERT INTO actor (id,name,gender,birth) VALUES (287,"Snyder, Mr. John Pillsbury","male","1959-9-25");
INSERT INTO actor (id,name,gender,birth) VALUES (288,"Mardirosian, Mr. Sarkis","male","1929-11-19");
INSERT INTO actor (id,name,gender,birth) VALUES (289,"Ford, Mr. Arthur","male","1947-5-14");
INSERT INTO actor (id,name,gender,birth) VALUES (290,"Rheims, Mr. George Alexander Lucien","male","1986-11-8");
INSERT INTO actor (id,name,gender,birth) VALUES (291,"Daly, Miss. Margaret Marcella Maggie  ","female","1984-6-26");
INSERT INTO actor (id,name,gender,birth) VALUES (292,"Nasr, Mr. Mustafa","male","1976-2-13");
INSERT INTO actor (id,name,gender,birth) VALUES (293,"Dodge, Dr. Washington","male","1938-6-18");
INSERT INTO actor (id,name,gender,birth) VALUES (294,"Wittevrongel, Mr. Camille","male","1998-2-11");
INSERT INTO actor (id,name,gender,birth) VALUES (295,"Angheloff, Mr. Minko","male","1966-11-9");
INSERT INTO actor (id,name,gender,birth) VALUES (296,"Laroche, Miss. Louise","female","1960-12-10");
INSERT INTO actor (id,name,gender,birth) VALUES (297,"Samaan, Mr. Hanna","male","1994-8-12");
INSERT INTO actor (id,name,gender,birth) VALUES (298,"Loring, Mr. Joseph Holland","male","1976-10-23");
INSERT INTO actor (id,name,gender,birth) VALUES (299,"Johansson, Mr. Nils","male","1934-1-9");
INSERT INTO actor (id,name,gender,birth) VALUES (300,"Olsson, Mr. Oscar Wilhelm","male","1990-6-17");
INSERT INTO actor (id,name,gender,birth) VALUES (301,"Malachard, Mr. Noel","male","1935-12-27");
INSERT INTO actor (id,name,gender,birth) VALUES (302,"Phillips, Mr. Escott Robert","male","1976-1-21");
INSERT INTO actor (id,name,gender,birth) VALUES (303,"Pokrnic, Mr. Tome","male","1935-2-5");
INSERT INTO actor (id,name,gender,birth) VALUES (304,"McCarthy, Miss. Catherine Katie  ","female","1962-7-7");
INSERT INTO actor (id,name,gender,birth) VALUES (305,"Crosby, Mrs. Edward Gifford (Catherine Elizabeth Halstead)","female","1958-1-9");
INSERT INTO actor (id,name,gender,birth) VALUES (306,"Allison, Mr. Hudson Joshua Creighton","male","1950-10-20");
INSERT INTO actor (id,name,gender,birth) VALUES (307,"Aks, Master. Philip Frank","male","1976-7-18");
INSERT INTO actor (id,name,gender,birth) VALUES (308,"Hays, Mr. Charles Melville","male","1942-12-2");
INSERT INTO actor (id,name,gender,birth) VALUES (309,"Hansen, Mrs. Claus Peter (Jennie L Howard)","female","1980-10-27");
INSERT INTO actor (id,name,gender,birth) VALUES (310,"Cacic, Mr. Jego Grga","male","1942-10-15");
INSERT INTO actor (id,name,gender,birth) VALUES (311,"Vartanian, Mr. David","male","1926-5-22");
INSERT INTO actor (id,name,gender,birth) VALUES (312,"Sadowitz, Mr. Harry","male","1942-10-29");
INSERT INTO actor (id,name,gender,birth) VALUES (313,"Carr, Miss. Jeannie","female","1962-10-2");
INSERT INTO actor (id,name,gender,birth) VALUES (314,"White, Mrs. John Stuart (Ella Holmes)","female","1986-5-18");
INSERT INTO actor (id,name,gender,birth) VALUES (315,"Hagardon, Miss. Kate","female","1956-5-19");
INSERT INTO actor (id,name,gender,birth) VALUES (316,"Spencer, Mr. William Augustus","male","1926-7-11");
INSERT INTO actor (id,name,gender,birth) VALUES (317,"Rogers, Mr. Reginald Harry","male","1954-6-25");
INSERT INTO actor (id,name,gender,birth) VALUES (318,"Jonsson, Mr. Nils Hilding","male","1943-4-6");
INSERT INTO actor (id,name,gender,birth) VALUES (319,"Jefferys, Mr. Ernest Wilfred","male","1987-3-17");
INSERT INTO actor (id,name,gender,birth) VALUES (320,"Andersson, Mr. Johan Samuel","male","1947-5-11");
INSERT INTO actor (id,name,gender,birth) VALUES (321,"Krekorian, Mr. Neshan","male","1944-2-16");
INSERT INTO actor (id,name,gender,birth) VALUES (322,"Nesson, Mr. Israel","male","1948-11-19");
INSERT INTO actor (id,name,gender,birth) VALUES (323,"Rowe, Mr. Alfred G","male","1949-10-5");
INSERT INTO actor (id,name,gender,birth) VALUES (324,"Kreuchen, Miss. Emilie","female","1983-11-17");
INSERT INTO actor (id,name,gender,birth) VALUES (325,"Assam, Mr. Ali","male","1920-12-7");
INSERT INTO actor (id,name,gender,birth) VALUES (326,"Becker, Miss. Ruth Elizabeth","female","1987-9-26");
INSERT INTO actor (id,name,gender,birth) VALUES (327,"Rosenshine, Mr. George (Mr George Thorne ) ","male","1964-2-21");
INSERT INTO actor (id,name,gender,birth) VALUES (328,"Clarke, Mr. Charles Valentine","male","1947-7-1");
INSERT INTO actor (id,name,gender,birth) VALUES (329,"Enander, Mr. Ingvar","male","1953-11-17");
INSERT INTO actor (id,name,gender,birth) VALUES (330,"Davies, Mrs. John Morgan (Elizabeth Agnes Mary White) ","female","1943-9-6");
INSERT INTO actor (id,name,gender,birth) VALUES (331,"Dulles, Mr. William Crothers","male","1922-12-4");
INSERT INTO actor (id,name,gender,birth) VALUES (332,"Thomas, Mr. Tannous","male","1968-10-28");
INSERT INTO actor (id,name,gender,birth) VALUES (333,"Nakid, Mrs. Said (Waika Mary  Mowad) ","female","1961-10-20");
INSERT INTO actor (id,name,gender,birth) VALUES (334,"Cor, Mr. Ivan","male","1937-11-4");
INSERT INTO actor (id,name,gender,birth) VALUES (335,"Maguire, Mr. John Edward","male","1989-9-4");
INSERT INTO actor (id,name,gender,birth) VALUES (336,"de Brito, Mr. Jose Joaquim","male","1981-12-18");
INSERT INTO actor (id,name,gender,birth) VALUES (337,"Elias, Mr. Joseph","male","1991-1-29");
INSERT INTO actor (id,name,gender,birth) VALUES (338,"Denbury, Mr. Herbert","male","1934-2-29");
INSERT INTO actor (id,name,gender,birth) VALUES (339,"Betros, Master. Seman","male","1933-12-19");
INSERT INTO actor (id,name,gender,birth) VALUES (340,"Fillbrook, Mr. Joseph Charles","male","1988-4-16");
INSERT INTO actor (id,name,gender,birth) VALUES (341,"Lundstrom, Mr. Thure Edvin","male","1966-5-1");
INSERT INTO actor (id,name,gender,birth) VALUES (342,"Sage, Mr. John George","male","1977-12-16");
INSERT INTO actor (id,name,gender,birth) VALUES (343,"Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake)","female","1975-7-13");
INSERT INTO actor (id,name,gender,birth) VALUES (344,"van Billiard, Master. James William","male","1974-9-11");
INSERT INTO actor (id,name,gender,birth) VALUES (345,"Abelseth, Miss. Karen Marie","female","1946-2-15");
INSERT INTO actor (id,name,gender,birth) VALUES (346,"Botsford, Mr. William Hull","male","1999-7-10");
INSERT INTO actor (id,name,gender,birth) VALUES (347,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)","female","1996-6-3");
INSERT INTO actor (id,name,gender,birth) VALUES (348,"Giles, Mr. Ralph","male","1927-9-24");
INSERT INTO actor (id,name,gender,birth) VALUES (349,"Walcroft, Miss. Nellie","female","1936-10-27");
INSERT INTO actor (id,name,gender,birth) VALUES (350,"Greenfield, Mrs. Leo David (Blanche Strouse)","female","1978-8-13");
INSERT INTO actor (id,name,gender,birth) VALUES (351,"Stokes, Mr. Philip Joseph","male","1990-11-29");
INSERT INTO actor (id,name,gender,birth) VALUES (352,"Dibden, Mr. William","male","1989-6-7");
INSERT INTO actor (id,name,gender,birth) VALUES (353,"Herman, Mr. Samuel","male","1930-1-1");
INSERT INTO actor (id,name,gender,birth) VALUES (354,"Dean, Miss. Elizabeth Gladys Millvina  ","female","1927-8-21");
INSERT INTO actor (id,name,gender,birth) VALUES (355,"Julian, Mr. Henry Forbes","male","1945-12-15");
INSERT INTO actor (id,name,gender,birth) VALUES (356,"Brown, Mrs. John Murray (Caroline Lane Lamson)","female","1956-12-11");
INSERT INTO actor (id,name,gender,birth) VALUES (357,"Lockyer, Mr. Edward","male","1953-2-1");
INSERT INTO actor (id,name,gender,birth) VALUES (358,"O'Keefe, Mr. Patrick","male","1994-8-4");
INSERT INTO actor (id,name,gender,birth) VALUES (359,"Lindell, Mrs. Edvard Bengtsson (Elin Gerda Persson)","female","1952-6-2");
INSERT INTO actor (id,name,gender,birth) VALUES (360,"Sage, Master. William Henry","male","1932-6-17");
INSERT INTO actor (id,name,gender,birth) VALUES (361,"Mallet, Mrs. Albert (Antoinette Magnin)","female","1942-9-21");
INSERT INTO actor (id,name,gender,birth) VALUES (362,"Ware, Mrs. John James (Florence Louise Long)","female","1992-6-15");
INSERT INTO actor (id,name,gender,birth) VALUES (363,"Strilic, Mr. Ivan","male","1936-7-23");
INSERT INTO actor (id,name,gender,birth) VALUES (364,"Harder, Mrs. George Achilles (Dorothy Annan)","female","1936-10-16");
INSERT INTO actor (id,name,gender,birth) VALUES (365,"Sage, Mrs. John (Annie Bullen)","female","1938-10-20");
INSERT INTO actor (id,name,gender,birth) VALUES (366,"Caram, Mr. Joseph","male","1926-7-11");
INSERT INTO actor (id,name,gender,birth) VALUES (367,"Riihivouri, Miss. Susanna Juhantytar Sanni  ","female","1932-4-29");
INSERT INTO actor (id,name,gender,birth) VALUES (368,"Gibson, Mrs. Leonard (Pauline C Boeson)","female","1966-4-23");
INSERT INTO actor (id,name,gender,birth) VALUES (369,"Pallas y Castello, Mr. Emilio","male","1934-12-4");
INSERT INTO actor (id,name,gender,birth) VALUES (370,"Giles, Mr. Edgar","male","1978-3-28");
INSERT INTO actor (id,name,gender,birth) VALUES (371,"Wilson, Miss. Helen Alice","female","1992-9-12");
INSERT INTO actor (id,name,gender,birth) VALUES (372,"Ismay, Mr. Joseph Bruce","male","1933-5-15");
INSERT INTO actor (id,name,gender,birth) VALUES (373,"Harbeck, Mr. William H","male","1974-11-19");
INSERT INTO actor (id,name,gender,birth) VALUES (374,"Dodge, Mrs. Washington (Ruth Vidaver)","female","1975-6-24");
INSERT INTO actor (id,name,gender,birth) VALUES (375,"Bowen, Miss. Grace Scott","female","1986-4-28");
INSERT INTO actor (id,name,gender,birth) VALUES (376,"Kink, Miss. Maria","female","1959-12-18");
INSERT INTO actor (id,name,gender,birth) VALUES (377,"Cotterill, Mr. Henry Harry  ","male","1924-12-19");
INSERT INTO actor (id,name,gender,birth) VALUES (378,"Hipkins, Mr. William Edward","male","1960-6-11");
INSERT INTO actor (id,name,gender,birth) VALUES (379,"Asplund, Master. Carl Edgar","male","1965-10-21");
INSERT INTO actor (id,name,gender,birth) VALUES (380,"O'Connor, Mr. Patrick","male","1958-2-1");
INSERT INTO actor (id,name,gender,birth) VALUES (381,"Foley, Mr. Joseph","male","1955-4-11");
INSERT INTO actor (id,name,gender,birth) VALUES (382,"Risien, Mrs. Samuel (Emma)","female","1932-5-6");
INSERT INTO actor (id,name,gender,birth) VALUES (383,"McNamee, Mrs. Neal (Eileen O'Leary)","female","1989-6-3");
INSERT INTO actor (id,name,gender,birth) VALUES (384,"Wheeler, Mr. Edwin Frederick  ","male","1961-3-25");
INSERT INTO actor (id,name,gender,birth) VALUES (385,"Herman, Miss. Kate","female","1997-2-29");
INSERT INTO actor (id,name,gender,birth) VALUES (386,"Aronsson, Mr. Ernst Axel Algot","male","1970-5-27");
INSERT INTO actor (id,name,gender,birth) VALUES (387,"Ashby, Mr. John","male","1970-9-19");
INSERT INTO actor (id,name,gender,birth) VALUES (388,"Canavan, Mr. Patrick","male","1954-5-22");
INSERT INTO actor (id,name,gender,birth) VALUES (389,"Palsson, Master. Paul Folke","male","1934-1-5");
INSERT INTO actor (id,name,gender,birth) VALUES (390,"Payne, Mr. Vivian Ponsonby","male","1940-1-17");
INSERT INTO actor (id,name,gender,birth) VALUES (391,"Lines, Mrs. Ernest H (Elizabeth Lindsey James)","female","1989-2-29");
INSERT INTO actor (id,name,gender,birth) VALUES (392,"Abbott, Master. Eugene Joseph","male","1984-2-11");
INSERT INTO actor (id,name,gender,birth) VALUES (393,"Gilbert, Mr. William","male","1960-1-21");
INSERT INTO actor (id,name,gender,birth) VALUES (394,"Kink-Heilmann, Mr. Anton","male","1924-3-18");
INSERT INTO actor (id,name,gender,birth) VALUES (395,"Smith, Mrs. Lucien Philip (Mary Eloise Hughes)","female","1954-7-29");
INSERT INTO actor (id,name,gender,birth) VALUES (396,"Colbert, Mr. Patrick","male","1930-6-7");
INSERT INTO actor (id,name,gender,birth) VALUES (397,"Frolicher-Stehli, Mrs. Maxmillian (Margaretha Emerentia Stehli)","female","1977-10-3");
INSERT INTO actor (id,name,gender,birth) VALUES (398,"Larsson-Rondberg, Mr. Edvard A","male","1966-12-2");
INSERT INTO actor (id,name,gender,birth) VALUES (399,"Conlon, Mr. Thomas Henry","male","1985-5-16");
INSERT INTO actor (id,name,gender,birth) VALUES (400,"Bonnell, Miss. Caroline","female","1967-3-25");
INSERT INTO actor (id,name,gender,birth) VALUES (401,"Gale, Mr. Harry","male","1926-2-18");
INSERT INTO actor (id,name,gender,birth) VALUES (402,"Gibson, Miss. Dorothy Winifred","female","1992-5-28");
INSERT INTO actor (id,name,gender,birth) VALUES (403,"Carrau, Mr. Jose Pedro","male","1958-9-8");
INSERT INTO actor (id,name,gender,birth) VALUES (404,"Frauenthal, Mr. Isaac Gerald","male","1951-9-20");
INSERT INTO actor (id,name,gender,birth) VALUES (405,"Nourney, Mr. Alfred (Baron von Drachstedt ) ","male","1932-11-25");
INSERT INTO actor (id,name,gender,birth) VALUES (406,"Ware, Mr. William Jeffery","male","1959-2-20");
INSERT INTO actor (id,name,gender,birth) VALUES (407,"Widener, Mr. George Dunton","male","1980-11-13");
INSERT INTO actor (id,name,gender,birth) VALUES (408,"Riordan, Miss. Johanna Hannah  ","female","1928-3-15");
INSERT INTO actor (id,name,gender,birth) VALUES (409,"Peacock, Miss. Treasteall","female","1932-9-12");
INSERT INTO actor (id,name,gender,birth) VALUES (410,"Naughton, Miss. Hannah","female","1980-6-10");
INSERT INTO actor (id,name,gender,birth) VALUES (411,"Minahan, Mrs. William Edward (Lillian E Thorpe)","female","1926-2-26");
INSERT INTO actor (id,name,gender,birth) VALUES (412,"Henriksson, Miss. Jenny Lovisa","female","1970-6-23");
INSERT INTO actor (id,name,gender,birth) VALUES (413,"Spector, Mr. Woolf","male","1925-11-24");
INSERT INTO actor (id,name,gender,birth) VALUES (414,"Oliva y Ocana, Dona. Fermina","female","1945-5-17");
INSERT INTO actor (id,name,gender,birth) VALUES (415,"Saether, Mr. Simon Sivertsen","male","1930-2-29");
INSERT INTO actor (id,name,gender,birth) VALUES (416,"Ware, Mr. Frederick","male","1957-9-20");
INSERT INTO actor (id,name,gender,birth) VALUES (417,"Peter, Master. Michael J","male","1949-8-23");
